server:
  port: 8081

spring:
  ai:
    google:
      genai:
#        project-id: ${GOOGLE_CLOUD_PROJECT_ID}
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.5-flash-lite
        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            options:
              model: gemini-embedding-001
              dimensions: 768
    mcp:
      client:
        stdio:
          connections:
            filesystem:
              command: npx
              args:
                - -y
                - "@modelcontextprotocol/server-filesystem"
                - "/tmp"
        streamable-http:
          connections:
            tavily:
              url: https://mcp.tavily.com
              endpoint: /mcp/?tavilyApiKey=${TAVILY_API_KEY}
        toolcallback:
          enabled: true
        initialized: false
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
        distance-type: COSINE_DISTANCE

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/springai
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.springframework.ai: DEBUG
    com.google.genai: DEBUG